### ISSUE TITLE
MPM figures not updated

### ISSUE THREAD

**Issue by Mike-Leo-Smith** [taichi-dev/taichi_benchmark#12]
Hi, I opened this [PR](https://github.com/taichi-dev/taichi_benchmark/issues/7) and it's been merged into the repo.

However, I found that the figures are not updated accordingly and old ones are still found in your recent articles (e.g., https://www.zhihu.com/question/540550599/answer/2550737011).

I'm afraid this could offer misleading information typically to new Taichi users. Would you mind updating the performance plots using the new implementations?

**Comment by qiao-bo** [comment]
Hi, thanks for the info. I have updated the MPM data in this repo using the latest results. We will also start bookkeeping all the improvement. @turbo0628 can you update the application plot we used in the articles? maybe we can add that plot in this repo 
as well?
